name: Demo Cart Agent

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/prompts/demo-cart-page.prompt.md'

jobs:
  create-issue:
    name: Create Issue from Prompt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub issue from prompt file
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('.github/prompts/demo-cart-page.prompt.md', 'utf8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Demo: Cart Page and Icon Implementation',
              body: 'This issue was created from the repository prompt file.\n\n---\n\n' + content
            });

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: create-issue
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build --workspace=api

      - name: Build Frontend
        run: npm run build --workspace=frontend

      - name: Run API tests (non-blocking)
        run: |
          npm run test:api || true
